### ISSUE TITLE
Can supercomputer help explore all for (4, 4, 4) and (5, 5, 5)? Or prove 23 for (3, 3, 3)?

### ISSUE THREAD

**Issue by ValZapod** [jakobmoosbauer/flips#1]
Also did you consider playing with commutative algorithms? 21 for (3, 3, 3) is here: https://www.sciencedirect.com/science/article/abs/pii/S0747717122000499 (free arxiv: https://arxiv.org/abs/1904.07683)

My public domain/CC0 code is here https://gcc.godbolt.org/z/9oszvM9aG

**Comment by jakobmoosbauer** [comment]
A full exploration of 4x4x4 or 5x5x5 would require computing a normal form of these schemes, which already takes longer than computing a normal form of 3x3x3 schemes, also the size of the graph probably is way too big. We are not aware of a way to use the flip graph to prove lower bounds. Already the layer 24 is so large that a full exploration of all layers of the graph is infeasible. Moreover, we do not know whether every solution is reachable from the standard algorithm, so computing the full graph up to layer 27 is not sufficient, we would have to go much higher.

We are working on a variant for commutative algorithms. Do you have some references what are the currently best bounds for commutative schemes for rectangular matrices?

**Comment by ValZapod** [comment]
>also the size of the graph probably is way too big.

Reading your paper you mention it is not even memory intensive. So why cannot supercomputer bruteforce through this?

>We are not aware of a way to use the flip graph to prove lower bounds.

If not prove, then bruteforce enough to increase probability 22 non-commutative algorithm for (3, 3, 3) does not exist.


>Do you have some references what are the currently best bounds for commutative schemes for rectangular matrices?

Bläser is for arbitrary fields, so (please correct me if I am wrong) > 19 lower bond for (3, 3, 3) is for commutative too. https://www.sciencedirect.com/science/article/pii/S0885064X02000079?via%3Dihub

This paper improves on Bläser for n >= 84: 
https://arxiv.org/pdf/1206.1530.pdf

**Comment by jakobmoosbauer** [comment]
> Reading your paper you mention it is not even memory intensive. So why cannot supercomputer bruteforce through this?

You probably underestimate the size of the graph, we already compute on over 2000 cores and bruteforcing through the whole graph this way would take forever. Moreover, if we wanted to bruteforce through the whole graph we would need to save every vertex of the graph so the procedure becomes memory intensive as well.

> > We are not aware of a way to use the flip graph to prove lower bounds.
> 
> If not prove, then bruteforce enough to increase probability 22 non-commutative algorithm for (3, 3, 3) does not exist.

To get a statement on the probability we would need know something about the probability distribution on the solution set that is generated by our search procedure, however, we do not know what the probability of finding a specific vertex is. There also is still the problem that we do not know whether we can find all components of the graph when starting from the standard algorithm. 

Personally I am quite convinced that there is no 22 algorithm that is reachable from the standard algorithm by flips, however, there is no sound probability I could give for that being true.

> > Do you have some references what are the currently best bounds for commutative schemes for rectangular matrices?
> 
> Bläser is for arbitrary fields, so (please correct me if I am wrong) >= 19 lower bond for (3, 3, 3) is for commutative too. https://www.sciencedirect.com/science/article/pii/S0885064X02000079?via%3Dihub
>

Bläser only is for bilinear algorithms as far as I understand, this automatically assumes non-commutativity, as a bilinear compuation also over a commutative domain is not allowed to use commutativity. 

My question was more towards upper bounds. https://www.sciencedirect.com/science/article/pii/S0304397510007036 gives a table with known commutative algorithms, except (3,3,3) with 21 multiplications, do you know any improvements upon the table given in the paper?

**Comment by ValZapod** [comment]
https://analyticsindiamag.com/meet-the-researchers-who-beat-deepmind-at-matrix-multiplication/

>Moosbauer believes that most of the results in the DeepMind paper, as well as their own results, are more like theoretical interests than purely mathematical.

In fact, the opposite is true, Google already wrote and compiled/verified HW silicon TPU that uses those results. https://www.assemblyai.com/blog/deepminds-alphatensor-explained/

And nvidia too? V100 microcode?

And they do appear to be practical, though OneMKL 2023.1 comparison is missing: https://towardsdatascience.com/understanding-deepmind-matrix-multiplication-c8dc49687ce7
